# 特徵分解

## 向量在特徵空間中的拆解與重建

此筆記展示：
1. 矩陣特徵分解
2. 向量投影到特徵向量基底
3. 從特徵空間重建
4. 驗證線性變換的一致性

In [ ]:
import numpy as np

# 1. 定義矩陣 A
A = np.array([[2, 1], [1, 2]])

# 2. 特徵分解
eigvals, eigvector = np.linalg.eig(A)
V_inv = np.linalg.inv(eigvector)

print("A =\n", A)
print("\n特徵值 Λ =\n", np.diag(eigvals))
print("\n特徵向量 V =\n", eigvector)

Back_A = eigvector @ np.diag(eigvals) @ V_inv
print("\n透過特徵分解重建 A =\n", Back_A)

A =
 [[2 1]
 [1 2]]

特徵值 Λ =
 [[3. 0.]
 [0. 1.]]

特徵向量 V =
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

透過特徵分解重建 A =
 [[2. 1.]
 [1. 2.]]


In [4]:
# 投影到特徵基底
c = V_inv @ A
print("\n在特徵基底下的座標 c =", c)

# 4. 重建
x_reconstructed = eigvector @ c
print("\n重建回原向量 =", x_reconstructed)

# # 誤差
# print("\n重建誤差 =", np.linalg.norm(x - x_reconstructed))

# # 5. 驗證 Ax
# Ax = A @ x

# Lambda = np.diag(eigvals)
# Lambda_c = Lambda @ c
# Ax_via_eig = V @ Lambda_c

# print("\nA x =", Ax)
# print("\n透過特徵分解計算的 A x =", Ax_via_eig)
# print("\nAx 誤差 =", np.linalg.norm(Ax - Ax_via_eig))


在特徵基底下的座標 c = [[ 2.12132034  2.12132034]
 [-0.70710678  0.70710678]]

重建回原向量 = [[2. 1.]
 [1. 2.]]
