# 特徵分解

## 向量在特徵空間中的拆解與重建

此筆記展示：
1. 矩陣特徵分解
2. 向量投影到特徵向量基底
3. 從特徵空間重建
4. 驗證線性變換的一致性

In [ ]:
import numpy as np

# 1. 定義矩陣 A
A = np.array([[2, 1], [1, 2]])

# 2. 特徵分解
eigvals, eigvector = np.linalg.eig(A)
V_inv = np.linalg.inv(eigvector)

print("A =\n", A)
print("\n特徵值 Λ =\n", np.diag(eigvals))
print("\n特徵向量 V =\n", eigvector)

Back_A = eigvector @ np.diag(eigvals) @ V_inv
print("\n透過特徵分解重建 A =\n", Back_A)

A =
 [[2 1]
 [1 2]]

特徵值 Λ =
 [[3. 0.]
 [0. 1.]]

特徵向量 V =
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

透過特徵分解重建 A =
 [[2. 1.]
 [1. 2.]]


### 數學說明

給定矩陣：

$$
A=
\begin{bmatrix}
2 & 1\\
1 & 2
\end{bmatrix}
$$

我們希望找到特徵分解：

$$
A = V\Lambda V^{-1}
$$

---

1. 求特徵值

$$
\det(A-\lambda I)=0
$$

$$
\det
\begin{bmatrix}
2-\lambda & 1\\
1 & 2-\lambda
\end{bmatrix}
=0
$$

$$
(2-\lambda)^2-1=0
$$

$$
\lambda^2-4\lambda+3=0
$$

$$
(\lambda-3)(\lambda-1)=0
$$

因此：

$$
\lambda_1=3,\qquad \lambda_2=1
$$

---

2. 求特徵向量

對應特徵向量可取：

$$
v_1=
\begin{bmatrix}
1\\
1
\end{bmatrix},
\qquad
v_2=
\begin{bmatrix}
1\\
-1
\end{bmatrix}
$$

組成矩陣：

$$
V=
\begin{bmatrix}
1 & 1\\
1 & -1
\end{bmatrix}
$$

$$
\Lambda=
\begin{bmatrix}
3 & 0\\
0 & 1
\end{bmatrix}
$$

---

3. 計算反矩陣

$$
V^{-1}
=
\frac{1}{-2}
\begin{bmatrix}
-1 & -1\\
-1 & 1
\end{bmatrix}
=
\begin{bmatrix}
\frac12 & \frac12\\
\frac12 & -\frac12
\end{bmatrix}
$$

---

## 4. 重建矩陣

$$
A = V\Lambda V^{-1}
$$

先計算：

$$
V\Lambda
=
\begin{bmatrix}
1 & 1\\
1 & -1
\end{bmatrix}
\begin{bmatrix}
3 & 0\\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
3 & 1\\
3 & -1
\end{bmatrix}
$$

再乘：

$$
V\Lambda V^{-1}
=
\begin{bmatrix}
3 & 1\\
3 & -1
\end{bmatrix}
\begin{bmatrix}
\frac12 & \frac12\\
\frac12 & -\frac12
\end{bmatrix}
=
\begin{bmatrix}
2 & 1\\
1 & 2
\end{bmatrix}
$$

---

5. 對應程式碼

```python
Back_A = eigvector @ np.diag(eigvals) @ V_inv
```

其數學意義為：

$$
A = V \Lambda V^{-1}
$$

即利用特徵值與特徵向量將原矩陣完整重建。

In [4]:
# 投影到特徵基底
c = V_inv @ A
print("\n在特徵基底下的座標 c =", c)

# 4. 重建
x_reconstructed = eigvector @ c
print("\n重建回原向量 =", x_reconstructed)

# # 誤差
# print("\n重建誤差 =", np.linalg.norm(x - x_reconstructed))

# # 5. 驗證 Ax
# Ax = A @ x

# Lambda = np.diag(eigvals)
# Lambda_c = Lambda @ c
# Ax_via_eig = V @ Lambda_c

# print("\nA x =", Ax)
# print("\n透過特徵分解計算的 A x =", Ax_via_eig)
# print("\nAx 誤差 =", np.linalg.norm(Ax - Ax_via_eig))


在特徵基底下的座標 c = [[ 2.12132034  2.12132034]
 [-0.70710678  0.70710678]]

重建回原向量 = [[2. 1.]
 [1. 2.]]


我們來玩一個經典的案例。我挑選一個數字漂亮、且能讓你清楚看到「縮放」效果的矩陣。
假設矩陣 A = \begin{pmatrix} 1 & 2 \\ 2 & 1 \end{pmatrix}。
### 第一步：找出特徵值 (\lambda)
我們解方程式 \det(A - \lambda I) = 0：


展開行列式：


因式分解得到：


**特徵值：\lambda_1 = 3 與 \lambda_2 = -1。**
### 第二步：找出特徵向量 (v)
**1. 當 \lambda_1 = 3 時：**


得到 -2x + 2y = 0 \implies x = y。
特徵向量 **v_1 = \begin{pmatrix} 1 \\ 1 \end{pmatrix}**。
**2. 當 \lambda_2 = -1 時：**


得到 2x + 2y = 0 \implies x = -y。
特徵向量 **v_2 = \begin{pmatrix} 1 \\ -1 \end{pmatrix}**。
### 第三步：組合回去（驗證 A = PDP^{-1}）
我們要準備三個零件：
 1. **P (特徵向量組合)：** \begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix}
 2. **D (對角特徵值)：** \begin{pmatrix} 3 & 0 \\ 0 & -1 \end{pmatrix}
 3. **P^{-1} (反矩陣)：** 使用公式 \frac{1}{ad-bc} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix}
   *    * **最後乘法驗證：**

先乘前兩個矩陣 (PD)：

再乘最後一個矩陣：
 * 左上角：3(1/2) + (-1)(1/2) = 1
 * 右上角：3(1/2) + (-1)(-1/2) = 2
 * 左下角：3(1/2) + (1)(1/2) = 2
 * 右下角：3(1/2) + (1)(-1/2) = 1
結果等於 **\begin{pmatrix} 1 & 2 \\ 2 & 1 \end{pmatrix}**。
### 這代表什麼意義？
這個計算過程證明了：原本看起來「混在一起」的矩陣指令 A，本質上就是在 (1,1) 方向拉長 3 倍，並在 (1,-1) 方向翻轉（-1 倍）。
你現在可以試著理解：如果我們把這個矩陣 A 連乘自己 n 次，其實就是在這些特徵向量的方向上重複縮放 n 次，這就是特徵值分解最強大的地方！
