# 矩陣數學入門：用 NumPy 學基本觀念

這份 Notebook 以高中生程度介紹矩陣的基本概念與常見運算。每個主題都包含簡短說明與一個 NumPy 程式範例。

建議學習方式：
1. 先閱讀文字說明。
2. 再執行程式碼。
3. 修改矩陣中的數字，觀察結果如何改變。


## 0. 準備工作：匯入 NumPy

NumPy 是 Python 中常用的數值運算套件。矩陣可以用 `numpy.array` 表示。


In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)
print("NumPy 版本：", np.__version__)

NumPy 版本： 2.3.5


## 1. 基本矩陣是什麼

矩陣是一個由數字排成的長方形表格，如果一個矩陣有 2 列、3 行，我們稱它是「2 × 3 矩陣」。

例如有 2 列、3 行的矩陣：

$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

> 機器學習中常常藉由矩陣的行列數來判斷資料運算的過程是否正確。

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("矩陣 A：")
print(A)

print("A 的形狀 shape：", A.shape)
print("列數：", A.shape[0])
print("行數：", A.shape[1])

矩陣 A：
[[1 2 3]
 [4 5 6]]
A 的形狀 shape： (2, 3)
列數： 2
行數： 3


## 2. 基本運算：加法、減法、純量乘法

兩個大小相同的矩陣可以相加或相減，方法是對應位置的元素相加或相減。

純量乘法是指用一個數去乘矩陣中的每一個元素。

In [ ]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[10, 20], [30, 40]])

print("A + B =")
print(A + B)

print("\nB - A =")
print(B - A)

print("\n3A =")
print(3 * A)

A + B =
[[11 22]
 [33 44]]

B - A =
[[ 9 18]
 [27 36]]

3A =
[[ 3  6]
 [ 9 12]]


## 3. 矩陣乘法

矩陣乘法不是對應位置相乘。  若 A 是 m × n 矩陣，B 是 n × p 矩陣，則 AB 會是 m × p 矩陣。

例如：

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}

B =
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

$$
A \cdot B =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix} = 
\begin{bmatrix}
1 * 5 + 2 * 7 & 1 * 6 + 2 * 8 \\
3 * 5 + 4 * 7 & 3 * 6 + 4 * 8
\end{bmatrix} = 
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$$

> 重點：A 的行數必須等於 B 的列數。

> 注意：通常 A @ B 不等於 B @ A。

在 NumPy 中，矩陣乘法可以使用 `@`。

In [ ]:
A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

print("A @ B =")
print(A @ B)

print("\nB @ A =")
print(B @ A)

print("\n注意：通常 A @ B 不等於 B @ A")

A @ B =
[[19 22]
 [43 50]]

B @ A =
[[23 34]
 [31 46]]

注意：通常 A @ B 不等於 B @ A


## 4. 單位矩陣

單位矩陣是主對角線為 1，其餘位置為 0 的方陣。

例如 3 × 3 單位矩陣：

$$
I =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

任何合適大小的矩陣 A 與單位矩陣相乘，結果仍是 A。

In [ ]:
A = np.array([[2, 3], [4, 5]])

I = np.eye(2)  # 產生一個 2x2 的單位矩陣

print("單位矩陣 I：")
print(I)

print("\nA @ I =")
print(A @ I)

print("\nI @ A =")
print(I @ A)

單位矩陣 I：
[[1. 0.]
 [0. 1.]]

A @ I =
[[2. 3.]
 [4. 5.]]

I @ A =
[[2. 3.]
 [4. 5.]]


## 5. 轉置矩陣

轉置矩陣是把矩陣的列與行交換。若 A 是 2 × 3 矩陣，則 A 的轉置會是 3 × 2 矩陣。  

在 NumPy 中，可以用 `.T` 取得轉置矩陣。

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("A =")
print(A)

print("\nA 的轉置 A.T =")
print(A.T)

print("\nA 的形狀：", A.shape)
print("A.T 的形狀：", A.T.shape)

A =
[[1 2 3]
 [4 5 6]]

A 的轉置 A.T =
[[1 4]
 [2 5]
 [3 6]]

A 的形狀： (2, 3)
A.T 的形狀： (3, 2)


## 6. 反矩陣

對於一個方陣 A，如果存在另一個矩陣 $A^{-1}$，使得：

$$
AA^{-1} = A^{-1}A = I
$$

那麼 $A^{-1}$ 稱為 A 的反矩陣。

不是每個方陣都有反矩陣。只有「可逆矩陣」才有反矩陣。

In [ ]:
A = np.array([[2, 1], [5, 3]])

A_inv = np.linalg.inv(A)

print("A =")
print(A)

print("\nA 的反矩陣 A_inv =")
print(A_inv)

print("\nA @ A_inv =")
print(A @ A_inv)

A =
[[2 1]
 [5 3]]

A 的反矩陣 A_inv =
[[ 3. -1.]
 [-5.  2.]]

A @ A_inv =
[[1. 0.]
 [0. 1.]]


## 7. 列運算：交換兩列

列運算是在線性代數中常用的工具。  
基本列運算包含：

1. 交換兩列。
2. 某一列乘上一個非零常數。
3. 某一列加上另一列的倍數。

這些操作常用來解線性方程組或找反矩陣。

In [ ]:
A = np.array([[1, 2], [3, 4]], dtype=float)

print("原矩陣 A：")
print(A)

# 交換第 0 列與第 1 列
A[[0, 1]] = A[[1, 0]]

print("\n交換兩列後：")
print(A)

原矩陣 A：
[[1. 2.]
 [3. 4.]]

交換兩列後：
[[3. 4.]
 [1. 2.]]


## 8. 列運算：某一列乘上常數

將某一列乘上一個非零常數，是基本列運算之一。這常用來把某個位置變成 1，方便進一步消去其他數字。

In [ ]:
A = np.array([[2, 4], [3, 6]], dtype=float)

print("原矩陣 A：")
print(A)

# 第 0 列除以 2，也就是乘上 1/2
A[0] = A[0] / 2

print("\n第 0 列除以 2 後：")
print(A)

原矩陣 A：
[[2. 4.]
 [3. 6.]]

第 0 列除以 2 後：
[[1. 2.]
 [3. 6.]]


## 9. 列運算：某一列加上另一列的倍數

這個運算常用於「消去」某個位置的數字。

例如，若第 1 列的第一個數字是 3，而第 0 列的第一個數字是 1，  
可以讓第 1 列減去 3 倍的第 0 列，使第 1 列第一個數字變成 0。

In [ ]:
A = np.array([[1, 2], [3, 7]], dtype=float)

print("原矩陣 A：")
print(A)

# 第 1 列 = 第 1 列 - 3 * 第 0 列
A[1] = A[1] - 3 * A[0]

print("\n第 1 列減去 3 倍第 0 列後：")
print(A)

原矩陣 A：
[[1. 2.]
 [3. 7.]]

第 1 列減去 3 倍第 0 列後：
[[1. 2.]
 [0. 1.]]


## 10. 基本行運算：交換兩行

行運算是對矩陣的「直行」做操作。  
在初等線性代數中，解方程組時最常使用的是列運算；但行運算也可以幫助理解矩陣結構。

這裡示範交換兩個行。

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

print("原矩陣 A：")
print(A)

# 交換第 0 行與第 2 行
A[:, [0, 2]] = A[:, [2, 0]]

print("\n交換第 0 行與第 2 行後：")
print(A)

原矩陣 A：
[[1. 2. 3.]
 [4. 5. 6.]]

交換第 0 行與第 2 行後：
[[3. 2. 1.]
 [6. 5. 4.]]


## 11. 線性方程組

線性方程組可以寫成矩陣形式：

$$
Ax = b
$$

例如：

$$
\begin{cases}
2x + y = 5 \\
x + 3y = 6
\end{cases}
$$

可以寫成：

$$
\begin{bmatrix}
2 & 1 \\
1 & 3
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
5 \\
6
\end{bmatrix}
$$

在 NumPy 中，可以用 `np.linalg.solve(A, b)` 求解。

In [ ]:
A = np.array([[2, 1], [1, 3]], dtype=float)

b = np.array([5, 6], dtype=float)

x = np.linalg.solve(A, b)

print("解 x =")
print(x)

print("\n檢查 A @ x =")
print(A @ x)

print("\n原本的 b =")
print(b)

解 x =
[1.8 1.4]

檢查 A @ x =
[5. 6.]

原本的 b =
[5. 6.]


## 12. 可逆矩陣

一個方陣若有反矩陣，就稱為可逆矩陣。

判斷 2 × 2 或更高階矩陣是否可逆，常見方式是看行列式是否不等於 0。  
若 `det(A) != 0`，A 通常是可逆矩陣。  
若 `det(A) == 0`，A 不可逆。

In [ ]:
A = np.array([[1, 2], [3, 4]], dtype=float)

B = np.array([[1, 2], [2, 4]], dtype=float)

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print("det(A) =", det_A)
print("det(B) =", det_B)

print("\nA 是否可逆：", not np.isclose(det_A, 0))
print("B 是否可逆：", not np.isclose(det_B, 0))

det(A) = -2.0000000000000004
det(B) = 0.0

A 是否可逆： True
B 是否可逆： False


## 13. 用反矩陣解線性方程組

若 $Ax = b$，且 A 可逆，則：

$$
x = A^{-1}b
$$

這是反矩陣的重要應用之一。  
不過在實際計算時，通常 `np.linalg.solve(A, b)` 比直接算反矩陣更穩定。

In [ ]:
A = np.array([[2, 1], [1, 3]], dtype=float)

b = np.array([5, 6], dtype=float)

A_inv = np.linalg.inv(A)
x_by_inverse = A_inv @ b
x_by_solve = np.linalg.solve(A, b)

print("用反矩陣求解：")
print(x_by_inverse)

print("\n用 np.linalg.solve 求解：")
print(x_by_solve)

用反矩陣求解：
[1.8 1.4]

用 np.linalg.solve 求解：
[1.8 1.4]


## 14. LU 分解

LU 分解是把一個矩陣 A 分解成兩個矩陣：

$$
A = LU
$$

其中：

- L 是下三角矩陣。
- U 是上三角矩陣。

LU 分解常用於有效率地解線性方程組。  
NumPy 本身沒有直接提供 LU 分解，因此這裡用一個簡單版本示範概念。

In [ ]:
def simple_lu(A):
    A = A.astype(float)
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()

    for i in range(n):
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j] = U[j] - factor * U[i]

    return L, U


A = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]], dtype=float)

L, U = simple_lu(A)

print("A =")
print(A)

print("\nL =")
print(L)

print("\nU =")
print(U)

print("\nL @ U =")
print(L @ U)

A =
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]

L =
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -1.  1.]]

U =
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]

L @ U =
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]


## 15. 綜合練習：用列運算把矩陣化簡

這個範例用基本列運算，把增廣矩陣逐步化簡。  
方程組是：

$$
\begin{cases}
x + y = 5 \\
2x + 3y = 13
\end{cases}
$$

增廣矩陣為：

$$
\begin{bmatrix}
1 & 1 & 5 \\
2 & 3 & 13
\end{bmatrix}
$$

目標是化成：

$$
\begin{bmatrix}
1 & 0 & x \\
0 & 1 & y
\end{bmatrix}
$$

In [ ]:
M = np.array([[1, 1, 5], [2, 3, 13]], dtype=float)

print("原增廣矩陣：")
print(M)

# R2 = R2 - 2R1
M[1] = M[1] - 2 * M[0]
print("\nR2 = R2 - 2R1：")
print(M)

# R1 = R1 - R2
M[0] = M[0] - M[1]
print("\nR1 = R1 - R2：")
print(M)

print("\n所以 x =", M[0, 2])
print("所以 y =", M[1, 2])

原增廣矩陣：
[[ 1.  1.  5.]
 [ 2.  3. 13.]]

R2 = R2 - 2R1：
[[1. 1. 5.]
 [0. 1. 3.]]

R1 = R1 - R2：
[[1. 0. 2.]
 [0. 1. 3.]]

所以 x = 2.0
所以 y = 3.0


## 學習總結

本 Notebook 介紹了：

- 矩陣的基本形式。
- 矩陣加法、減法、純量乘法與矩陣乘法。
- 單位矩陣與轉置矩陣。
- 反矩陣與可逆矩陣。
- 基本列運算與基本行運算。
- 線性方程組的矩陣表示與求解。
- LU 分解的基本概念。

後續可以進一步學習：行列式、向量空間、線性變換、特徵值與特徵向量。
